services:

  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-db
    environment:
      POSTGRES_DB: ewm-stats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - stats_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ewm-stats" ]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  stats-server:
    build:
      context: ./stats-service/server
      dockerfile: Dockerfile
    container_name: ewm-stats-server
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      SERVER_PORT: 9090
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/ewm-stats
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      HIBERNATE_DDL_AUTO: none
      JPA_SHOW_SQL: "false"
      TZ: "UTC"
    ports:
      - "9090:9090"
    restart: unless-stopped

volumes:
  stats_db_data:


