spring.application.name=ewm-stats-service

# Server Configuration
server.port=${SERVER_PORT:9090}


# DataSource
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm-stats}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}


# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:none}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.jdbc.time_zone=${TZ:UTC}

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.encoding=UTF-8

# Logging
logging.level.org.springframework.boot.autoconfigure.sql.init=INFO
logging.level.org.springframework.jdbc.datasource.init=INFO
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO

#logging.level.org.hibernate.tool.hbm2ddl=DEBUG
#logging.level.org.springframework.jdbc.datasource.init.ScriptUtils=DEBUG
#logging.level.org.springframework.transaction.interceptor=TRACE
#logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG