CREATE TABLE IF NOT EXISTS endpoint_hit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR NOT NULL,
    ip VARCHAR(64) NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_endpoint_hit_ts      ON endpoint_hit (timestamp);
CREATE INDEX IF NOT EXISTS idx_endpoint_hit_uri_ts  ON endpoint_hit (uri, timestamp);